from typing import Any, Dict, Iterator, List, Mapping, Optional, Tuple

ABI = List[Dict[str, Any]]

class _LazyABIRegistry(Mapping[str, ABI]):
    @property
    def AAVE_V1_ATOKEN(self) -> ABI: ...
    @property
    def AAVE_V1_LENDING_POOL(self) -> ABI: ...
    @property
    def AAVE_V1_LENDING_POOL_ADDRESSES_PROVIDER(self) -> ABI: ...
    @property
    def AAVE_V1_LENDING_POOL_CORE(self) -> ABI: ...
    @property
    def AAVE_V2_COLLECTOR(self) -> ABI: ...
    @property
    def AAVE_V2_INCENTIVES_CONTROLLER(self) -> ABI: ...
    @property
    def AAVE_V2_LENDING_POOL(self) -> ABI: ...
    @property
    def AAVE_V2_LENDING_POOL_ADDRESSES_PROVIDER(self) -> ABI: ...
    @property
    def AAVE_V2_LENDING_POOL_ADDRESSES_PROVIDER_REGISTRY(self) -> ABI: ...
    @property
    def AAVE_V2_LENDING_POOL_COLLATERAL_MANAGER(self) -> ABI: ...
    @property
    def AAVE_V2_LENDING_POOL_CONFIGURATOR(self) -> ABI: ...
    @property
    def AAVE_V2_LENDING_RATE_ORACLE(self) -> ABI: ...
    @property
    def AAVE_V2_POOL_ADMIN(self) -> ABI: ...
    @property
    def AAVE_V2_PRICE_ORACLE(self) -> ABI: ...
    @property
    def AAVE_V2_PROTOCAL_DATA_PROVIDER(self) -> ABI: ...
    @property
    def AAVE_V2_UI_INCENTIVE_DATA_PROVIDER(self) -> ABI: ...
    @property
    def AAVE_V2_UI_POOL_DATA_PROVIDER(self) -> ABI: ...
    @property
    def AAVE_V2_WETH_GATEWAY(self) -> ABI: ...
    @property
    def AERODROME_SLIPSTREAM_V3_FACTORY(self) -> ABI: ...
    @property
    def AERODROME_SLIPSTREAM_V3_ROUTER(self) -> ABI: ...
    @property
    def CHAINLINK_AGGREGATOR_V3(self) -> ABI: ...
    @property
    def ERC1155(self) -> ABI: ...
    @property
    def ERC1271(self) -> ABI: ...
    @property
    def ERC165(self) -> ABI: ...
    @property
    def ERC20(self) -> ABI: ...
    @property
    def ERC20_PERMIT(self) -> ABI: ...
    @property
    def ERC2981(self) -> ABI: ...
    @property
    def ERC4626(self) -> ABI: ...
    @property
    def ERC721(self) -> ABI: ...
    @property
    def ERC777(self) -> ABI: ...
    @property
    def JOE_V2_FACTORY(self) -> ABI: ...
    @property
    def JOE_V2_PAIR(self) -> ABI: ...
    @property
    def JOE_V2_ROUTER(self) -> ABI: ...
    @property
    def LFJ_LIQUIDITY_BOOK_V2_2_FACTORY(self) -> ABI: ...
    @property
    def LFJ_LIQUIDITY_BOOK_V2_2_ROUTER(self) -> ABI: ...
    @property
    def MULTICALL3(self) -> ABI: ...
    @property
    def OPENZEPPELIN_ACCESS_CONTROL_V5(self) -> ABI: ...
    @property
    def OPENZEPPELIN_IERC1967(self) -> ABI: ...
    @property
    def PANCAKE_V3_BASE_FACTORY(self) -> ABI: ...
    @property
    def PANCAKE_V3_FACTORY(self) -> ABI: ...
    @property
    def PANCAKE_V3_IPERIPHERY_PAYMENTS_WITH_FEE(self) -> ABI: ...
    @property
    def PANCAKE_V3_MASTER_CHEF_V3(self) -> ABI: ...
    @property
    def PANCAKE_V3_NON_FUNGIBLE_POSITION_MANAGER(self) -> ABI: ...
    @property
    def PANCAKE_V3_POOL_V3(self) -> ABI: ...
    @property
    def PANCAKE_V3_QUOTER(self) -> ABI: ...
    @property
    def PANCAKE_V3_QUOTER_V2(self) -> ABI: ...
    @property
    def PANCAKE_V3_ROUTER_V3(self) -> ABI: ...
    @property
    def PANCAKE_V3_SELF_PERMIT(self) -> ABI: ...
    @property
    def PANCAKE_V3_SMART_ROUTER(self) -> ABI: ...
    @property
    def PANCAKE_V3_STAKER(self) -> ABI: ...
    @property
    def SHADOW_CLMM_V3_FACTORY(self) -> ABI: ...
    @property
    def SHADOW_CLMM_V3_ROUTER(self) -> ABI: ...
    @property
    def UNISWAP_BSC_ROUTER(self) -> ABI: ...
    @property
    def UNISWAP_PERMIT2(self) -> ABI: ...
    @property
    def UNISWAP_V1_EXCHANGE(self) -> ABI: ...
    @property
    def UNISWAP_V1_FACTORY(self) -> ABI: ...
    @property
    def UNISWAP_V2_FACTORY(self) -> ABI: ...
    @property
    def UNISWAP_V2_PAIR(self) -> ABI: ...
    @property
    def UNISWAP_V2_ROUTER(self) -> ABI: ...
    @property
    def UNISWAP_V3_FACTORY(self) -> ABI: ...
    @property
    def UNISWAP_V3_MULTICALL(self) -> ABI: ...
    @property
    def UNISWAP_V3_NON_FUNGIBLE_POSITION_MANAGE(self) -> ABI: ...
    @property
    def UNISWAP_V3_POOL(self) -> ABI: ...
    @property
    def UNISWAP_V3_QUOTER(self) -> ABI: ...
    @property
    def UNISWAP_V3_ROUTER(self) -> ABI: ...
    @property
    def UNISWAP_V3_ROUTER_02(self) -> ABI: ...
    @property
    def VELODROME_SLIPSTREAM_V3_FACTORY(self) -> ABI: ...
    @property
    def VELODROME_SLIPSTREAM_V3_ROUTER(self) -> ABI: ...
    @property
    def WETH9(self) -> ABI: ...
    def __getitem__(self, name: str) -> ABI: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: object) -> bool: ...
    def copy(self) -> Dict[str, ABI]: ...
    def to_dict(self) -> Dict[str, ABI]: ...

ABIS: _LazyABIRegistry
ALL_ABIS_NAME: List[str]

def all_abis() -> Tuple[List[str], Mapping[str, ABI]]: ...
def get_abi(name: str) -> ABI: ...
def clear_abi_cache() -> None: ...
def loaded_abis() -> List[str]: ...
def get_abi_from_address(
    address: str, api_key: str, chain_api: str
) -> Optional[str]: ...
