from typing import Any, Dict, Iterator, List, Mapping, Optional, Tuple, Union

ABI = List[Dict[str, Any]]

class _LazyABIRegistry(Mapping[str, ABI]):
    @property
    def AAVE_V2_LENDING_POOL_ADDRESSES_PROVIDER(self) -> ABI: ...
    @property
    def AERODROME_SLIPSTREAM_V3_FACTORY(self) -> ABI: ...
    @property
    def AERODROME_SLIPSTREAM_V3_ROUTER(self) -> ABI: ...
    @property
    def CHAINLINK_AGGREGATOR_V3(self) -> ABI: ...
    @property
    def ERC1271(self) -> ABI: ...
    @property
    def ERC165(self) -> ABI: ...
    @property
    def ERC20_PERMIT(self) -> ABI: ...
    @property
    def ERC2981(self) -> ABI: ...
    @property
    def ERC4626(self) -> ABI: ...
    @property
    def ERC5267(self) -> ABI: ...
    @property
    def ERC6093_ERC1155_ERRORS(self) -> ABI: ...
    @property
    def ERC6093_ERC20_ERRORS(self) -> ABI: ...
    @property
    def ERC6093_ERC721_ERRORS(self) -> ABI: ...
    @property
    def ERC6909(self) -> ABI: ...
    @property
    def ERC6909_METADATA(self) -> ABI: ...
    @property
    def LFJ_LIQUIDITY_BOOK_V2_2_FACTORY(self) -> ABI: ...
    @property
    def LFJ_LIQUIDITY_BOOK_V2_2_ROUTER(self) -> ABI: ...
    @property
    def MULTICALL3(self) -> ABI: ...
    @property
    def OPENZEPPELIN_ACCESS_CONTROL_V5(self) -> ABI: ...
    @property
    def OPENZEPPELIN_IERC1967(self) -> ABI: ...
    @property
    def PANCAKE_V3_BASE_FACTORY(self) -> ABI: ...
    @property
    def PANCAKE_V3_FACTORY(self) -> ABI: ...
    @property
    def PANCAKE_V3_POOL_V3(self) -> ABI: ...
    @property
    def PANCAKE_V3_ROUTER_V3(self) -> ABI: ...
    @property
    def PANCAKE_V3_SMART_ROUTER(self) -> ABI: ...
    @property
    def SHADOW_CLMM_V3_FACTORY(self) -> ABI: ...
    @property
    def SHADOW_CLMM_V3_ROUTER(self) -> ABI: ...
    @property
    def UNISWAP_PERMIT2(self) -> ABI: ...
    @property
    def UNISWAP_V1_EXCHANGE(self) -> ABI: ...
    @property
    def UNISWAP_V2_FACTORY(self) -> ABI: ...
    @property
    def UNISWAP_V2_ROUTER(self) -> ABI: ...
    @property
    def UNISWAP_V3_FACTORY(self) -> ABI: ...
    @property
    def UNISWAP_V3_POOL_EVENTS(self) -> ABI: ...
    @property
    def UNISWAP_V3_POOL_STATE(self) -> ABI: ...
    @property
    def UNISWAP_V3_ROUTER_02(self) -> ABI: ...
    @property
    def VELODROME_SLIPSTREAM_V3_FACTORY(self) -> ABI: ...
    @property
    def VELODROME_SLIPSTREAM_V3_ROUTER(self) -> ABI: ...
    def __getitem__(self, name: str) -> ABI: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: object) -> bool: ...
    def copy(self) -> Dict[str, ABI]: ...
    def to_dict(self) -> Dict[str, ABI]: ...

ABIS: _LazyABIRegistry
ALL_ABIS_NAME: List[str]

def all_abis() -> Tuple[List[str], Mapping[str, ABI]]: ...
def get_abi(name: str) -> ABI: ...
def get_abi_info(name: str) -> Dict[str, Any]: ...
def find_abis(
    contract_role: Optional[str] = ...,
    interface_name: Optional[str] = ...,
    provenance_status: Optional[str] = ...,
) -> List[str]: ...
def clear_abi_cache() -> None: ...
def loaded_abis() -> List[str]: ...
def get_abi_from_address(
    address: str,
    api_key: str,
    chain_api: Optional[Union[str, int]] = ...,
    *,
    chain_id: Optional[int] = ...,
) -> Optional[str]: ...
